import React from 'react';
import { Send, Star, ShieldCheck } from 'lucide-react';
import { Card, CardBody } from '../ui/Card';

export const AnalyticsStats = ({ totalGenerations, averageRating }) => {
  const cards = [
    {
      title: 'Total Script Generations',
      value: totalGenerations || 0,
      icon: Send,
      color: 'bg-indigo-50 text-indigo-600',
      description: 'Upsell scripts generated by staff'
    },
    {
      title: 'Average AI Script Rating',
      value: averageRating ? `${Number(averageRating).toFixed(1)} / 5.0` : '0.0 / 5.0',
      icon: Star,
      color: 'bg-amber-50 text-amber-500',
      description: 'Average score submitted by sales reps'
    },
    {
      title: 'AI Pipeline Status',
      value: 'Optimal',
      icon: ShieldCheck,
      color: 'bg-emerald-50 text-emerald-600',
      description: 'Gemini-2.5-flash response rating'
    }
  ];

  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
      {cards.map((card, index) => {
        const Icon = card.icon;
        return (
          <Card key={index} className="hover:shadow-md transition-all duration-200">
            <CardBody className="flex items-center gap-5">
              <div className={`p-4 rounded-2xl ${card.color} shrink-0`}>
                <Icon className="w-7 h-7" />
              </div>
              <div className="min-w-0">
                <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider">
                  {card.title}
                </p>
                <p className="text-2xl font-bold text-slate-900 mt-1 leading-none">
                  {card.value}
                </p>
                <p className="text-xs text-slate-500 mt-2 font-medium">
                  {card.description}
                </p>
              </div>
            </CardBody>
          </Card>
        );
      })}
    </div>
  );
};
