const safeParse = (val) => {
  if (Array.isArray(val)) return val;
  if (typeof val === 'string') {
    try { return JSON.parse(val); } catch { return []; }
  }
  return [];
};

export function generateScriptTxt(record) {
  const recommendedUpgrade = record.recommended_upgrade || 'Package Upgrade';
  const upgradePrice = record.upgrade_price || '';
  const whyUpgrade = safeParse(record.why_upgrade);
  const suggestedScript = record.suggested_script || record.ai_response;
  const pricingComparison = record.pricing_comparison || '';
  const expectedBenefits = safeParse(record.expected_benefits);
  const objectionHandling = safeParse(record.objection_handling);

  return `
=========================================
MANIVTHA TOURS & TRAVELS - AI UPSELL SCRIPT
=========================================
Customer: ${record.customer_name || 'Customer'}
Destination: ${record.destination || 'Destination'}
Staff Member: ${record.staff_name || 'Staff'}
Date: ${new Date(record.created_at).toLocaleDateString()}

RECOMMENDED UPGRADE:
${recommendedUpgrade}${upgradePrice ? ` — ${upgradePrice}` : ''}

PRICING COMPARISON:
${pricingComparison || 'N/A'}

WHY UPGRADE:
${whyUpgrade.map(item => `- ${item}`).join('\n')}

SUGGESTED SALES SCRIPT:
"${suggestedScript}"

EXPECTED BENEFITS:
${expectedBenefits.map(item => `- ${item}`).join('\n')}

${objectionHandling.length > 0 ? `OBJECTION HANDLING:\n${objectionHandling.map((item, i) => `Objection ${i + 1}: ${item.objection || ''}\nResponse: ${item.rebuttal || ''}\n`).join('\n')}` : ''}
-----------------------------------------
Generated by Manivtha AI Upsell Assistant.
Confidence: ${record.confidence_score || 'High'} | Est. Tokens: ${record.token_cost || 0}
  `.trim();
}

export function downloadScriptTxt(record) {
  const textContent = generateScriptTxt(record);
  const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `upsell_script_${(record.customer_name || 'customer').replace(/\s+/g, '_')}.txt`;
  link.click();
  URL.revokeObjectURL(url);
}
